package org.projeto_mvc.view;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.projeto_mvc.model.Feriado;
import org.projeto_mvc.view.tablemodel.FeriadoTableModel;
import org.projeto_mvc.view.util.DiasUteis;

/**
 *
 * @author carol
 */
public class IFrameCalcularDias extends javax.swing.JInternalFrame {

    public IFrameCalcularDias() {
        initComponents();
        setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPaneDatas = new javax.swing.JPanel();
        txtMnsg = new javax.swing.JLabel();
        txtDias = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jFormattedTxtFinal = new javax.swing.JFormattedTextField();
        jFormattedTxtInicial = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Calcular dias úteis");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPaneDatas.setBackground(new java.awt.Color(255, 255, 255));
        jPaneDatas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insira os dados", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPaneDatas.setForeground(new java.awt.Color(0, 0, 0));

        txtMnsg.setFont(new java.awt.Font("Alef", 0, 18)); // NOI18N
        txtMnsg.setForeground(new java.awt.Color(0, 0, 0));
        txtMnsg.setText("Total de dias:");

        txtDias.setBackground(new java.awt.Color(0, 0, 0));
        txtDias.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtDias.setForeground(new java.awt.Color(0, 0, 0));
        txtDias.setText("xxx");

        btnCalcular.setBackground(new java.awt.Color(51, 153, 255));
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jFormattedTxtFinal.setBackground(new java.awt.Color(242, 245, 246));
        jFormattedTxtFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTxtFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTxtFinalActionPerformed(evt);
            }
        });

        jFormattedTxtInicial.setBackground(new java.awt.Color(242, 245, 246));
        jFormattedTxtInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTxtInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTxtInicialActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Intervalo de tempo");

        btnLimpar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneDatasLayout = new javax.swing.GroupLayout(jPaneDatas);
        jPaneDatas.setLayout(jPaneDatasLayout);
        jPaneDatasLayout.setHorizontalGroup(
            jPaneDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneDatasLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPaneDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTxtInicial)
                    .addComponent(jFormattedTxtFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPaneDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneDatasLayout.createSequentialGroup()
                        .addComponent(txtMnsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDias))
                    .addGroup(jPaneDatasLayout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar)))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPaneDatasLayout.setVerticalGroup(
            jPaneDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneDatasLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTxtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMnsg)
                    .addComponent(txtDias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCalcular)
                        .addComponent(btnLimpar))
                    .addComponent(jFormattedTxtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jTable1.setBackground(new java.awt.Color(245, 245, 245));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPaneDatas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPaneDatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 874, 523);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTxtInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTxtInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTxtInicialActionPerformed

    private void jFormattedTxtFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTxtFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTxtFinalActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //vai chamar o metodo calcular dias uteis
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        ArrayList<Feriado> listaFeriados = new ArrayList<>();
        FeriadoTableModel feriadoTableModel = new FeriadoTableModel(new ArrayList<>());

        jTable1.setModel(feriadoTableModel);

        if (validarForm()) {
            DiasUteis diasUteis = new DiasUteis();
            try {
                listaFeriados = diasUteis.obterFeriados(LocalDate.parse(jFormattedTxtInicial.getText(), formatter), LocalDate.parse(jFormattedTxtFinal.getText(), formatter));
            } catch (SQLException ex) {
                Logger.getLogger(IFrameCalcularDias.class.getName()).log(Level.SEVERE, null, ex);
            }
            long resulDiasUteis = diasUteis.contarDiasUteisComFeriados(LocalDate.parse(jFormattedTxtInicial.getText(), formatter), LocalDate.parse(jFormattedTxtFinal.getText(), formatter), listaFeriados);
            System.out.println("Numero de dias uteis é: " + resulDiasUteis);
            txtDias.setText(String.valueOf(resulDiasUteis));
            
            feriadoTableModel = new FeriadoTableModel(listaFeriados);
            jTable1.setModel(feriadoTableModel);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
        txtDias.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private boolean validarForm() {
        if (jFormattedTxtInicial.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Data Incial", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            jFormattedTxtInicial.requestFocus();
            return false;
        }
        if (jFormattedTxtFinal.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Data Final", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            jFormattedTxtFinal.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IFrameCalcularDias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IFrameCalcularDias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IFrameCalcularDias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IFrameCalcularDias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IFrameCalcularDias().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JFormattedTextField jFormattedTxtFinal;
    private javax.swing.JFormattedTextField jFormattedTxtInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPaneDatas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtDias;
    private javax.swing.JLabel txtMnsg;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        jFormattedTxtFinal.setText("");
        jFormattedTxtInicial.setText("");
    }
}
